config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  
  resources :restaurants, except: [:destroy] do
    resources :reviews, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
                                    message: ': Only chinese, italian, japanese, french or
                                    belgian categories accepted' }
end

app/models/review.rb
class Review < ApplicationRecord
  # A review must belong to a restaurant.
  belongs_to :restaurant
  # A review must have a content.
  validates :content, presence: true
  # A review must have a rating.
  # A review’s rating must be a number between 0 and 5.
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: (0..5).to_a }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /restaurants/1 or /restaurants/1.json
  # def destroy
  #   @restaurant.destroy

  #   respond_to do |format|
  #     format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # We need to find the restaurant associated with the review
  before_action :set_restaurant, only: %i[new create]

  # def new
  # end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar bg-light">
      <div class="container container-fluid">
        <%= link_to "Yelp MVP", root_path, class: "navbar-brand" %>
      </div>
    </nav>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div class="list-group-item list-group-item-action" aria-current="true" id="<%= dom_id restaurant %>">
  <div class="d-flex justify-content-between align-items-center">
    <h3>
      <%= restaurant.name %>
    </h3>

    <p>
      <strong>Category:</strong>
      <%= restaurant.category %>
    </p>
  </div>
  <div class="d-flex justify-content-between align-items-center">
    <p>
      <strong>Address:</strong>
      <%= restaurant.address %>
    </p>

    <p>
      <strong>Phone number:</strong>
      <%= restaurant.phone_number %>
    </p>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit this restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Go to this restaurant", @restaurant, class: "btn btn-outline-primary" %>
  <%= link_to "Back to restaurants", restaurants_path, class: "btn btn-outline-primary" %>
</div>

app/views/restaurants/index.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>All Restaurants</h1>
  <%= link_to "Add Restaurant", new_restaurant_path, class: "btn btn-primary"%>
</div>

<div class="list-group">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <%= link_to "Show me this restaurant", restaurant, class: "btn btn-outline-primary" %>
    <br>
  <% end %>

</div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path, class: "btn btn-outline-primary" %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<h3 class="mt-3">Current reviews</h3>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"> ⭐️ <%= review.rating %> <br> <%= review.content %></li>
  <% end %>
</ul>
<br>

<div>
  <div class="d-flex justify-content-between algn-items-center">
    <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant), class: "btn btn-outline-primary" %>
    <%= link_to "Back to restaurants", restaurants_path, class: "btn btn-outline-primary" %>
  </div>

  <h3 class="mt-5">Write a review</h3>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>

</div>